# Site settings
<<<<<<< HEAD
title: Ebn's Blog
SEOTitle: Ebn's Blog
header-img: img/wp_004.jpg
email: ebnbin@outlook.com
description: ""
keyword: ""
url: "http://ebnbin.com/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
=======
title: Your Blog
SEOTitle: 你的博客 | Your Blog
header-img: img/home-bg.jpg
email: huxpro@gmail.com
description: ""
keyword: ""
url: "http://huangxuan.me"              # your host, for absolute URL
baseurl: "/huxblog-boilerplate"         # for example, '/blog' if your blog hosted on 'host/blog'
>>>>>>> huxpro/master



# SNS settings
RSS: false
<<<<<<< HEAD
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    ebnbin
#twitter_username:  huxpro
#facebook_username:  huxpro
=======
weibo_username:     huxpro
zhihu_username:     huxpro
github_username:    huxpro
#twitter_username:  huxpro
facebook_username:  huxpro
>>>>>>> huxpro/master



# Build settings
<<<<<<< HEAD
=======
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
>>>>>>> huxpro/master
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



<<<<<<< HEAD
=======
# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



>>>>>>> huxpro/master
# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
<<<<<<< HEAD
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
=======

>>>>>>> huxpro/master


# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
<<<<<<< HEAD
#duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing
=======
duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing
>>>>>>> huxpro/master




# Analytics settings
# Baidu Analytics
<<<<<<< HEAD
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me
=======
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me
>>>>>>> huxpro/master



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
<<<<<<< HEAD
#sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，多玩玩看看。"
#sidebar-avatar: /img/ebnbin.png      # use absolute URL, seeing it's used in both `/` and `/about/`
=======
sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，多玩玩看看。"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
>>>>>>> huxpro/master



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
<<<<<<< HEAD
#    },{
#        title: "Foo",
#        href: "#"
#    },{
#        title: "Bar",
#        href: "#"
#    },{
#        title: "Example Friends",
#        href: "#"
#    },{
#        title: "It helps SEO",
#        href: "#"
    }
]

# Fix: "Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file."
gems: [jekyll-paginate]
=======
    },{
        title: "Foo",
        href: "#"
    },{
        title: "Bar",
        href: "#"
    },{
        title: "Example Friends",
        href: "#"
    },{
        title: "It helps SEO",
        href: "#"
    }
]
>>>>>>> huxpro/master
